# wrangler.toml
name = "tuwa-player"
compatibility_date = "2024-09-23"
pages_build_output_dir = "_site"

# SEARCH WORKER BINDING (Crucial for your AI Search)
[[services]]
binding = "AI"
service = "ai-search-worker"  # Ensure this matches your worker's name

[site]
bucket = "./_site"